- name: Install nginx
  ansible.legacy.dnf:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: Deploy custom index page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  become: yes


